apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opssight
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PavanAnganna90/PlatformOps-2.0.git
    targetRevision: HEAD
    path: charts/opssight
  destination:
    server: https://kubernetes.default.svc
    namespace: opssight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true